// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwwrqzlzxywffuixmipi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3d3Jxemx6eHl3ZmZ1aXhtaXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0Nzc5MzYsImV4cCI6MjA1NTA1MzkzNn0.ZKw0hXxdAdqr4U4WTY2N5N4eJKiU59nq4R19eo1oR-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);