// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkahwajajmksvqsvdqif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYWh3YWpham1rc3Zxc3ZkcWlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzOTQwMjEsImV4cCI6MjA1NDk3MDAyMX0.v7QghTMmpX4qOvhnEvXLGn0RzyA_m-LoGLx26He8wM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);